[mypy]
files = src/admin_extra_buttons, tests/demoapp/demo/backends.py, tests/demoapp/demo/admin.py
mypy_path = $MYPY_CONFIG_FILE_DIR/src/:$MYPY_CONFIG_FILE_DIR/tests/demoapp
;enable_error_code =
;    deprecated,
;    ignore-without-code
plugins =
    mypy_django_plugin.main

strict = true

[mypy.plugins.django-stubs]
django_settings_module = demo.settings

[mypy-demo.models.*]
ignore_errors = true
ignore_missing_imports = True

[mypy-demo.upload.*]
ignore_errors = true
ignore_missing_imports = True
