[pytest]
django_find_project = false
pythonpath = ./tests/demoapp/ ./src
DJANGO_SETTINGS_MODULE = demo.settings
norecursedirs = "demo", ".tox"
addopts =
    --tb=short
    --capture=no
    --echo-version=django
    --echo-attr=django.conf.settings.DATABASES.default.ENGINE
    --cov=admin_extra_buttons
    --cov-report=html
    --cov-report=xml
    --cov-config=tests/.coveragerc

;python_files = "tests/test_*.py tests/**/test_*.py src/*.py"
markers =
    functional: mark a test as functional
    selenium: selenium test
    skip: skip test

;
;[tool.coverage]
;run.source = [
;  "admin_sync",
;]
;run.dynamic_context = "test_function"
;run.branch = true
;run.parallel = true
;run.omit = [
;  "**/create_extra_permissions.py",
;]
;run.plugins = [
;  "covdefaults",
;]
;report.fail_under = 80
;report.show_missing = true
;report.exclude_lines = [
;  "pragma: no cover",
;]
;html.show_contexts = true
;html.skip_covered = false
;paths.source = [
;  "src",
;  ".tox*/*/lib/python*/site-packages",
;  ".tox*/pypy*/site-packages",
;  ".tox*\\*\\Lib\\site-packages",
;  "*/src",
;  "*\\src",
;]
