[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    docs
    d{52, 42, 32}-type
    pkg_meta
    d{42, 32}-py{39}
    d{52}-py{313}
skip_missing_interpreters = true

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d52: django==5.2.*
pass_env =
    PGHOST
    PGPORT
    PYTHONDONTWRITEBYTECODE
commands =
    pytest --cov=admin_extra_buttons --cov-report=xml --junitxml {toxworkdir}{/}junit-{envname}.xml -o junit_family=legacy {posargs:tests}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
skip_install = false
commands =
    mkdocs build -d ./~build/docs
dependency_groups = docs

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --no-config {env_tmp_dir}

[testenv:d32-type]
commands =
    {[type]commands}
base = type

[testenv:d42-type]
commands =
    {[type]commands}
base = type

[testenv:d52-type]
commands =
    {[type]commands}
base = type

[testenv:mypy]
deps =
    django==5.2.*
commands =
    mypy --config mypy.ini {posargs:}
dependency_groups =
    dev
    type-check

[type]
description = run type check on code base
commands =
    mypy --config mypy.ini {posargs:}
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d52: django==5.2.*
dependency_groups =
    dev
    d32: type-check
    d42: type-check
    d52: type-check
