[tox]
requires =
    tox>=4.2
    tox-gh-actions
    tox-uv>=1.20.2
env_list =
    lint
    docs
    type
    pkg_meta
    d{42, 32}-py{312, 311, 310, 39}
    d{51}-py{313, 312, 311, 310}
skip_missing_interpreters = true

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d51: django==5.1.*
pass_env =
    PGHOST
    PGPORT
    PYTHONDONTWRITEBYTECODE
commands =
    pytest --cov=admin_extra_buttons --cov-report=xml --junitxml {toxworkdir}{/}junit-{envname}.xml -o junit_family=legacy {posargs:tests}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
skip_install = false
commands =
    mkdocs build -d ./~build/docs
dependency_groups = docs, type-check, dj

[testenv:type]
description = run type check on code base
commands =
    mypy --strict src/
dependency_groups = type-check, dev

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --no-config {env_tmp_dir}
