[tox]
requires =
    tox>=4.2
    tox-uv>=1.25
env_list =
    lint
    mypy
    docs
    pkg_meta
    d{60, 52, 42}-py{314, 313, 312}
skip_missing_interpreters = true

[testenv]
package = wheel
wheel_build_env = .pkg
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d52: django==5.2.*
    d60: django==6.0.*
pass_env =
    PGHOST
    PGPORT
    PYTHONDONTWRITEBYTECODE
commands =
    pytest --cov=admin_extra_buttons --cov-report=xml --junitxml {toxworkdir}{/}junit-{envname}.xml -o junit_family=legacy {posargs:tests}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
pass_env =
    HOMEPATH
    PROGRAMDATA
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:mypy]
runner = uv-venv-lock-runner
description = run mypy type checking
skip_install = false
commands =
    mypy --config-file mypy.ini {posargs:src/}
    mypy --config-file mypy.ini {posargs:tests/demoapp/}
dependency_groups = type-check

[testenv:docs]
skip_install = false
commands =
    mkdocs build -d ./~build/docs
dependency_groups = docs

[testenv:pkg_meta]
description = check that the long description is valid
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist --wheel --out-dir {env_tmp_dir} .
    twine check {env_tmp_dir}{/}*
    check-wheel-contents --no-config {env_tmp_dir}
