name: Lint

on:
  push:
    branches:
      - '**'        # matches every branch
    tags-ignore: [ "**" ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-lint"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  attestations: write
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    outputs:
      lint: ${{steps.changes.outputs.lint }}
      mypy: ${{steps.changes.outputs.mypy }}
      package: ${{steps.changes.outputs.package }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: changes
        name: Check for file changes
        uses: dorny/paths-filter@v3 # v3.0.0
        with:
          base: ${{ github.ref }}
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  lint:
    needs: changes
    runs-on: ubuntu-latest
    if: needs.changes.outputs.lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install tox
      - name: Static Code checks
        run: tox -e lint

  package:
    needs: changes
    if: needs.changes.outputs.package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install tox
      - name: Check Python Package structure
        run: tox -e pkg_meta

  mypy:
    needs: changes
    if: needs.changes.outputs.mypy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        django: [ "52", "42", "32" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install tox
      - name: Type Checking
        run: tox -e d${{ matrix.django }}-type
